# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forecedetectionwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from VizWindow import Ui_VizWindow


class Ui_force_detection_window(QtWidgets.QWidget, object):
    def __init__(self, controller, channels):
        from view import EMGWindow
        super(Ui_force_detection_window, self).__init__()
        self.channels = channels
        self.controller = controller
        self.view = EMGWindow(self)
        self.vizui = Ui_VizWindow(self, self)
        self.forceui = Ui_force_detection_window
        self.forceui.setObjectName(self, "forecedetectionwindow")
        self.forceui.resize(self, 384, 280)
        self.onset = None
        self.offset = None

    def setupforceUi(self, forecedetectionwindow):
        self.centralwidget = QtWidgets.QWidget(forecedetectionwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 30, 101, 141))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(250, 50, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(250, 90, 113, 25))
        self.lineEdit_3.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(250, 130, 113, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 50, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 90, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Yrsa")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 210, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(forecedetectionwindow)
        QtCore.QMetaObject.connectSlotsByName(forecedetectionwindow)

    def retranslateUi(self, forecedetectionwindow):
        _translate = QtCore.QCoreApplication.translate
        forecedetectionwindow.setWindowTitle(_translate("forecedetectionwindow", "Onset and offset force detection"))
        self.label.setText(_translate("forecedetectionwindow", "Channels"))
        self.label_2.setText(_translate("forecedetectionwindow", "Triggers"))
        self.label_5.setText(_translate("forecedetectionwindow", "Onset"))
        self.label_4.setText(_translate("forecedetectionwindow", "Offset"))
        self.label_6.setText(_translate("forecedetectionwindow", "Peak"))
        self.pushButton.setText(_translate("forecedetectionwindow", "Detect"))
        self.pushButton.clicked.connect(self.detect_force)

    def detect_force(self):
        selected_channels = [item.text() for item in self.listWidget.selectedItems()]
        print("Selected Channels:", selected_channels)
        # # Obtention des index des canaux sélectionnés
        # channel_indices = self.controller.get_channel_indices(selected_channels)
        # print("Channel Indices:", channel_indices)
        self.onset = self.lineEdit_2.text().strip()
        self.offset = self.lineEdit_3.text().strip()
        peak = self.lineEdit_4.text().strip()
        self.window = QtWidgets.QMainWindow()
        onset = self.onset
        offset = self.offset
        self.vizui.comboBox.addItem(onset)  # Add onset value to comboBoxOnset
        self.vizui.comboBox_2.addItem(offset)  # Add offset value to comboBoxOffset
        self.controller.detect_force(selected_channels, onset, offset, peak)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    forecedetectionwindow = QtWidgets.QMainWindow()
    ui = Ui_force_detection_window()
    ui.setupUi(forecedetectionwindow)
    forecedetectionwindow.show()
    sys.exit(app.exec_())
