# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SegmentationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegmentationWindow(QtWidgets.QWidget, object):
    def __init__(self, controller, events_ids):
        from view import EMGWindow
        super(Ui_SegmentationWindow, self).__init__()
        self.controller = controller
        self.view = EMGWindow
        self.events_ids = events_ids
        self.segui = Ui_SegmentationWindow
        self.segui.setObjectName(self, "SegmentationWindow")
        self.segui.resize(self, 346, 304)

        self.setupsegUi(self)

    def setupsegUi(self, SegmentationWindow):
        self.centralwidget = QtWidgets.QWidget(SegmentationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(220, 30, 111, 121))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 60, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 190, 41, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 41, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 190, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 220, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 220, 89, 25))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(SegmentationWindow)
        QtCore.QMetaObject.connectSlotsByName(SegmentationWindow)

    def retranslateUi(self, SegmentationWindow):
        _translate = QtCore.QCoreApplication.translate
        SegmentationWindow.setWindowTitle(_translate("SegmentationWindow", "Segment based on events"))
        self.label.setText(_translate("SegmentationWindow", "Segment on events :"))
        self.label_2.setText(_translate("SegmentationWindow", "Tmin"))
        self.label_3.setText(_translate("SegmentationWindow", "Tmax"))
        self.pushButton.setText(_translate("SegmentationWindow", "Segment"))
        self.pushButton.clicked.connect(self.segment)

    def segment(self):
        tmin = float(self.lineEdit.text())
        tmax = float(self.lineEdit_2.text())
        code_t0 = [item.text() for item in self.listWidget.selectedItems()]
        self.controller.segment(code_t0, tmin, tmax)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SegmentationWindow = QtWidgets.QMainWindow()
    ui = Ui_SegmentationWindow()
    ui.setupUi(SegmentationWindow)
    SegmentationWindow.show()
    sys.exit(app.exec_())
