# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TriggersWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TriggersWindow(QtWidgets.QWidget, object):
    def __init__(self, controller):
        from view import EMGWindow
        super(Ui_TriggersWindow, self).__init__()
        self.controller = controller
        self.view = EMGWindow
        self.trigui = Ui_TriggersWindow
        self.trigui.setObjectName(self, "TriggersWindow")
        self.trigui.resize(self, 296, 381)
        self.setuptrigUi(self)

    def setuptrigUi(self, TriggersWindow):
        self.centralwidget = QtWidgets.QWidget(TriggersWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 71, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 91, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 91, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 190, 91, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 220, 131, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 10, 141, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(150, 40, 141, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(150, 70, 141, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(150, 100, 141, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 160, 141, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(150, 130, 141, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(150, 190, 141, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(150, 220, 141, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(100, 250, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(100, 295, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.retranslateUi(TriggersWindow)
        QtCore.QMetaObject.connectSlotsByName(TriggersWindow)

    def retranslateUi(self, TriggersWindow):
        _translate = QtCore.QCoreApplication.translate
        TriggersWindow.setWindowTitle(_translate("TriggersWindow", "Set triggers"))
        self.label.setText(_translate("TriggersWindow", "Red left :"))
        self.label_2.setText(_translate("TriggersWindow", "Red right :"))
        self.label_3.setText(_translate("TriggersWindow", "Green left :"))
        self.label_4.setText(_translate("TriggersWindow", "Green right :"))
        self.label_5.setText(_translate("TriggersWindow", "Onset :"))
        self.label_6.setText(_translate("TriggersWindow", "Offset :"))
        self.label_7.setText(_translate("TriggersWindow", "Peak :"))
        self.label_8.setText(_translate("TriggersWindow", "Response triggers :"))
        self.pushButton.setText(_translate("TriggersWindow", "Set triggers"))
        self.pushButton.clicked.connect(self.set_triggers)

        self.pushButton_2.setText(_translate("TriggersWindow", "Cancel"))
        self.pushButton_2.clicked.connect(self.close)

    def set_triggers(self):
        # Get the trigger values from the line edits
        trig_id = {
            'red_left': self.lineEdit.text().strip(),
            'red_right': self.lineEdit_2.text().strip(),
            'green_left': self.lineEdit_3.text().strip(),
            'green_right': self.lineEdit_4.text().strip()
        }
        emg_id = {
            'onset': self.lineEdit_5.text().strip(),
            'offset': self.lineEdit_6.text().strip(),
            'peak': self.lineEdit_7.text().strip()
        }
        resp_list = [int(x) for x in self.lineEdit_8.text().split()]
        trig_values = trig_id.values()
        emg_values = emg_id.values()
        resp_values = resp_list
        self.controller.store_user_inputs(int(trig_values), int(emg_values), resp_values)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    TriggersWindow = QtWidgets.QMainWindow()
    ui = Ui_TriggersWindow()
    ui.setupUi(TriggersWindow)
    TriggersWindow.show()
    sys.exit(app.exec_())
