# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VizWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VizWindow(QtWidgets.QWidget, object):
    def __init__(self, controller, events_ids):
        from view import EMGWindow
        super(Ui_VizWindow, self).__init__()
        self.controller = controller
        self.view = EMGWindow
        self.events_ids = events_ids
        self.vizui = Ui_VizWindow
        self.vizui.setObjectName(self, "VizWindow")
        self.vizui.resize(self, 480, 376)
        self.setupvizUi(self)

    def setupvizUi(self, VizWindow):
        self.centralwidget = QtWidgets.QWidget(VizWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 290, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(290, 40, 151, 192))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 10, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 220, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 220, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 270, 41, 17))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 270, 113, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 90, 86, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(0, 90, 86, 25))
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(140, 60, 61, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.retranslateUi(VizWindow)
        QtCore.QMetaObject.connectSlotsByName(VizWindow)

    def retranslateUi(self, VizWindow):
        _translate = QtCore.QCoreApplication.translate
        VizWindow.setWindowTitle(_translate("VizWindow", "Viz"))
        self.pushButton.setText(_translate("VizWindow", "Viz"))
        self.pushButton.clicked.connect(self.viz)
        self.label.setText(_translate("VizWindow", "Id Events"))
        self.label_2.setText(_translate("VizWindow", "tmin"))
        self.label_3.setText(_translate("VizWindow", "tmax"))
        self.label_4.setText(_translate("VizWindow", "Onset"))
        self.label_5.setText(_translate("VizWindow", "Offset"))

    def viz(self):
        onset = self.comboBox.currentText()
        offset = self.comboBox_2.currentText()
        code_t0 = [item.text() for item in self.listWidget.selectedItems()]
        tmin = float(self.lineEdit.text())
        tmax = float(self.lineEdit_2.text())
        self.controller.viz(code_t0, tmin, tmax, onset, offset)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    VizWindow = QtWidgets.QMainWindow()
    ui = Ui_VizWindow()
    ui.setupUi(VizWindow)
    VizWindow.show()
    sys.exit(app.exec_())
